#!/bin/bash

# Test sheep recovery logic when node of number of copies down

. ./common

for i in `seq 0 3`; do
    _start_sheep $i
done

_wait_for_sheep 4

_cluster_format -c 2

$DOG vdi create test 100M -P

_kill_sheep 1 &
_kill_sheep 2 &
_wait_for_sheep_recovery 0

_start_sheep 2 &
_wait_for_sheep_recovery 0
$DOG vdi check test
