#!/bin/bash

# Test vdi deletion of empty volume

. ./common

for i in `seq 0 2`; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format -c 3

$DOG vdi create test 4T
$DOG vdi delete test &

sleep 3
_vdi_list

